# Generated by Django 4.2.2 on 2023-07-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0002_questionpost_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Question", "verbose_name_plural": "Questions"},
        ),
        migrations.AlterModelOptions(
            name="questionpost",
            options={
                "verbose_name": "QuestionPost",
                "verbose_name_plural": "QuestionsPost",
            },
        ),
        migrations.AlterField(
            model_name="question",
            name="reciever",
            field=models.ManyToManyField(
                related_name="reciever_user", to="accounts.proile"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="sender",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.proile",
            ),
        ),
        migrations.AlterField(
            model_name="questionpost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.proile"
            ),
        ),
    ]
