# Generated by Django 4.2.2 on 2023-07-04 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_question_options_alter_questionpost_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="reciever",
        ),
    ]
