# Generated by Django 4.2.2 on 2023-07-15 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_question_reciever"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_body",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="questionpost",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answars",
                to="core.question",
            ),
        ),
    ]
