# Generated by Django 4.2.2 on 2023-07-01 21:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_question_options_alter_questionpost_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Proile",
            new_name="Profile",
        ),
    ]
