# Generated by Django 4.2.2 on 2023-07-01 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_proile_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="facbook",
            new_name="facebook",
        ),
    ]
