# Generated by Django 4.2.2 on 2023-07-19 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("askfm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["-question"],
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["-question"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
    ]
