# Generated by Django 4.2.2 on 2023-07-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("askfm", "0002_alter_answer_options_alter_question_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="privet",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
