# Generated by Django 4.2.2 on 2023-07-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("askfm", "0003_question_privet_alter_question_anonymous"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="privet",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.TextField(null=True),
        ),
    ]
